// Sprite-based avatar. Each layer is a Phaser Image/Sprite loaded from the
// sprite sheets in public/assets/sprites/ (generated by scripts/generate-placeholders.mjs).
// When real pixel-art assets arrive, drop in the PNGs — no code changes needed.
//
// Coordinate system (Container origin):
//   (0, 0) = center of character, vertically centered at body mid-point
//   Body: setOrigin(0.5, 0.5), fills -16..+16 on Y at SPRITE_SCALE=0.5
//   Face:  setOrigin(0.5, 0.5), positioned at head center (~y=-6)
//   Hair:  setOrigin(0.5, 1),   positioned at head top (~y=-16)
//
// Layer depths match CLAUDE.md spec (0=body … 9=accessory2).

import Phaser from 'phaser';
import type { AvatarConfig } from '../types/avatar';
import { DEFAULT_AVATAR } from '../types/avatar';
import { useOfficeStore } from '../store/useOfficeStore';

const SPRITE_SCALE = 0.5;               // 64px frames → 32px display
const BODY_HALF    = 32 * SPRITE_SCALE;  // 16px half-height

// All body-sized (64×64) sprites share the same center — transparent pixels
// in the real art handle visual placement. Face parts (16×16) sit at head center.
const BODY_Y        =  0;                  // center of all 64×64 sprites
const HEAD_CENTER_Y = -BODY_HALF + 8;      // -8  (head top at -16, head ≈ top 25%)
const ACC_Y         = HEAD_CENTER_Y;

// Depth constants — matches CLAUDE.md spec
const D = {
  body:       0,
  bottom:     1,
  top:        2,
  shoes:      3,
  eyebrow:    4,
  eyes:       5,
  mouth:      6,
  hair:       7,
  accessory1: 8,
  accessory2: 9,
} as const;

// Exported so OfficeScene can compute the HTML label world-Y
export const AVATAR_LABEL_OFFSET_Y = BODY_HALF + 4; // 20px below center (feet + margin)

export class AvatarSprite extends Phaser.GameObjects.Container {
  private bodySprite!:   Phaser.GameObjects.Sprite;
  private bottomSprite!: Phaser.GameObjects.Sprite;
  private topSprite!:    Phaser.GameObjects.Sprite;
  private shoesImg!:     Phaser.GameObjects.Image;
  private eyebrowImg!:   Phaser.GameObjects.Image;
  private eyesImg!:      Phaser.GameObjects.Image;
  private mouthImg!:     Phaser.GameObjects.Image;
  private hairImg!:      Phaser.GameObjects.Image;
  private acc1Img!:      Phaser.GameObjects.Image | null;
  private acc2Img!:      Phaser.GameObjects.Image | null;
  private statusDot!:    Phaser.GameObjects.Graphics;
  private assignDot!:    Phaser.GameObjects.Graphics;

  private cfg: AvatarConfig;
  private dir: 'front' | 'back';
  readonly userId: string;
  displayName: string;

  constructor(
    scene: Phaser.Scene,
    x: number,
    y: number,
    userId: string,
    cfg: AvatarConfig  = DEFAULT_AVATAR,
    facing: 'front' | 'back' = 'front',
    displayName = '',
    statusColor  = 0x22c55e,
    assignColor  = 0x22c55e,
  ) {
    super(scene, x, y);
    this.userId = userId;
    this.cfg    = { ...cfg };
    this.dir    = facing;
    this.displayName = displayName;
    scene.add.existing(this);

    this.buildLayers();
    this.buildDots(statusColor, assignColor);
    this.applyConfig();

    this.setSize(32, 36);
    this.setInteractive({ cursor: 'pointer' });
    this.on('pointerdown', () => useOfficeStore.getState().setSelectedUser(this.userId));
    this.on('pointerover',  () => { scene.game.canvas.style.cursor = 'pointer'; });
    this.on('pointerout',   () => { scene.game.canvas.style.cursor = 'default'; });
  }

  // ── Public API ─────────────────────────────────────────────────────────────

  updateConfig(cfg: AvatarConfig): void {
    this.cfg = { ...cfg };
    this.applyConfig();
  }

  setFacing(facing: 'front' | 'back'): void {
    if (this.dir === facing) return;
    this.dir = facing;
    this.applyFacing();
  }

  setDisplayName(name: string): void { this.displayName = name; }

  setStatusColor(color: number): void {
    this.statusDot.clear();
    this.statusDot.fillStyle(color, 1);
    this.statusDot.fillCircle(0, 0, 3);
  }

  setAssignDotColor(color: number): void {
    this.assignDot.clear();
    this.assignDot.fillStyle(color, 1);
    this.assignDot.fillCircle(0, 0, 4);
  }

  /** Called by OfficeScene when a tween starts. */
  startWalk(): void {
    const dir = this.dir;
    const tone = this.cfg.skinTone;
    const tp   = String(this.cfg.topId).padStart(2, '0');
    const bp   = String(this.cfg.bottomId).padStart(2, '0');
    this.bodySprite.play(`walk_${dir}_${tone}`, true);
    this.topSprite.play(`walk_${dir}_top_${tp}`, true);
    this.bottomSprite.play(`walk_${dir}_bottom_${bp}`, true);
  }

  /** Called by OfficeScene when a tween completes. */
  stopWalk(): void {
    const dir  = this.dir;
    const tone = this.cfg.skinTone;
    const tp   = String(this.cfg.topId).padStart(2, '0');
    const bp   = String(this.cfg.bottomId).padStart(2, '0');
    this.bodySprite.play(`idle_${dir}_${tone}`, true);
    this.topSprite.play(`idle_${dir}_top_${tp}`, true);
    this.bottomSprite.play(`idle_${dir}_bottom_${bp}`, true);
  }

  // ── Build ──────────────────────────────────────────────────────────────────

  private buildLayers(): void {
    const s = this.scene;

    // Body (Sprite for walk animation)
    this.bodySprite = s.add.sprite(0, BODY_Y, `body_${this.cfg.skinTone}`, 0);
    this.bodySprite.setOrigin(0.5, 0.5).setScale(SPRITE_SCALE).setDepth(D.body);

    // Bottom (Sprite)
    this.bottomSprite = s.add.sprite(0, BODY_Y, `bottom_01`, 0);
    this.bottomSprite.setOrigin(0.5, 0.5).setScale(SPRITE_SCALE).setDepth(D.bottom);

    // Top (Sprite)
    this.topSprite = s.add.sprite(0, BODY_Y, `top_01`, 0);
    this.topSprite.setOrigin(0.5, 0.5).setScale(SPRITE_SCALE).setDepth(D.top);

    // Shoes (Image — shares 64×64 origin with body; real art places shoes only at bottom)
    this.shoesImg = s.add.image(0, BODY_Y, 'shoes_all', 0);
    this.shoesImg.setOrigin(0.5, 0.5).setScale(SPRITE_SCALE).setDepth(D.shoes);

    // Face parts (16×16 frames, centered on head)
    this.eyebrowImg = s.add.image(0, HEAD_CENTER_Y - 2, 'face_eyebrows', 0);
    this.eyebrowImg.setOrigin(0.5, 0.5).setScale(SPRITE_SCALE).setDepth(D.eyebrow);

    this.eyesImg = s.add.image(0, HEAD_CENTER_Y, 'face_eyes', 0);
    this.eyesImg.setOrigin(0.5, 0.5).setScale(SPRITE_SCALE).setDepth(D.eyes);

    this.mouthImg = s.add.image(0, HEAD_CENTER_Y + 3, 'face_mouth', 0);
    this.mouthImg.setOrigin(0.5, 0.5).setScale(SPRITE_SCALE).setDepth(D.mouth);

    // Hair (Image — frame 0=front, frame 1=back; shares 64×64 frame with body)
    this.hairImg = s.add.image(0, BODY_Y, `hair_01`, 0);
    this.hairImg.setOrigin(0.5, 0.5).setScale(SPRITE_SCALE).setDepth(D.hair);

    this.acc1Img = null;
    this.acc2Img = null;

    this.add([
      this.bodySprite, this.bottomSprite, this.topSprite,
      this.shoesImg, this.eyebrowImg, this.eyesImg, this.mouthImg,
      this.hairImg,
    ]);
  }

  private buildDots(statusColor: number, assignColor: number): void {
    this.statusDot = this.scene.add.graphics();
    this.statusDot.setDepth(10).setPosition(18, HEAD_CENTER_Y);
    this.statusDot.fillStyle(statusColor, 1);
    this.statusDot.fillCircle(0, 0, 3);

    this.assignDot = this.scene.add.graphics();
    this.assignDot.setDepth(11).setPosition(0, -BODY_HALF - 8);
    this.assignDot.fillStyle(assignColor, 1);
    this.assignDot.fillCircle(0, 0, 4);

    this.add([this.statusDot, this.assignDot]);
  }

  // ── Apply config ───────────────────────────────────────────────────────────

  private applyConfig(): void {
    const { skinTone, topId, bottomId, shoeId, hairStyle,
            eyeType, mouthType, eyebrowType, accessory1, accessory2 } = this.cfg;
    const dir  = this.dir;
    const tone = skinTone;
    const tp   = String(topId).padStart(2, '0');
    const bp   = String(bottomId).padStart(2, '0');
    const hp   = String(hairStyle).padStart(2, '0');

    // Body skin
    this.bodySprite.setTexture(`body_${tone}`, dir === 'front' ? 0 : 5);

    // Clothing
    this.topSprite.setTexture(`top_${tp}`, dir === 'front' ? 0 : 5);
    this.bottomSprite.setTexture(`bottom_${bp}`, dir === 'front' ? 0 : 5);

    // Shoes (col = shoeId-1, row0=front/row1=back)
    const shoeFrame = (dir === 'front' ? 0 : 10) + (shoeId - 1);
    this.shoesImg.setFrame(shoeFrame);
    this.shoesImg.setTexture('shoes_all', shoeFrame);

    // Hair
    this.hairImg.setTexture(`hair_${hp}`, dir === 'front' ? 0 : 1);

    // Face (col = typeId-1, always row 0)
    const eyeFrame     = eyeType     - 1;
    const browFrame    = eyebrowType - 1;
    const mouthFrame   = mouthType   - 1;
    this.eyesImg.setFrame(eyeFrame);
    this.eyebrowImg.setFrame(browFrame);
    this.mouthImg.setFrame(mouthFrame);

    // Accessories
    this.applyAccessory(1, accessory1, dir);
    this.applyAccessory(2, accessory2, dir);

    this.applyFacing();
  }

  private applyFacing(): void {
    const front = this.dir === 'front';

    // Face parts hidden when back-facing
    this.eyesImg.setVisible(front);
    this.eyebrowImg.setVisible(front);
    this.mouthImg.setVisible(front);

    // Body / hair / clothing switch frame
    const bodyFrame = front ? 0 : 5;
    this.bodySprite.setFrame(bodyFrame);
    this.hairImg.setFrame(front ? 0 : 1);

    const tp = String(this.cfg.topId).padStart(2, '0');
    const bp = String(this.cfg.bottomId).padStart(2, '0');
    this.topSprite.setTexture(`top_${tp}`, bodyFrame);
    this.bottomSprite.setTexture(`bottom_${bp}`, bodyFrame);

    const shoeFrame = (front ? 0 : 10) + (this.cfg.shoeId - 1);
    this.shoesImg.setFrame(shoeFrame);

    if (this.acc1Img) {
      const f = (front ? 0 : 10) + ((this.cfg.accessory1 ?? 1) - 1);
      this.acc1Img.setFrame(f);
    }
    if (this.acc2Img) {
      const f = (front ? 0 : 10) + ((this.cfg.accessory2 ?? 1) - 1);
      this.acc2Img.setFrame(f);
    }
  }

  private applyAccessory(slot: 1 | 2, id: number | null, dir: 'front' | 'back'): void {
    const imgProp: 'acc1Img' | 'acc2Img' = slot === 1 ? 'acc1Img' : 'acc2Img';
    const depth = slot === 1 ? D.accessory1 : D.accessory2;

    if (id === null) {
      if (this[imgProp]) { this[imgProp]!.destroy(); this[imgProp] = null; }
      return;
    }

    const frame = (dir === 'front' ? 0 : 10) + (id - 1);
    if (!this[imgProp]) {
      const img = this.scene.add.image(0, ACC_Y, 'accessories_all', frame);
      img.setOrigin(0.5, 0.5).setScale(SPRITE_SCALE).setDepth(depth);
      this.add(img);
      this[imgProp] = img;
    } else {
      this[imgProp]!.setFrame(frame);
    }
  }
}
